# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 042ec2e2ffec3a8dfac191d6386ad49aa3f4cd912e14ff8523d627a4d81e6ccb9243cb923181b975668d0f8fc374151fe51f07179e19607a23f0a689aafff6dd

test:
  secret_key_base: a5f3bf5d5f62cb68e28415b519a194ff573c4aa37411c4c0bc6cc7162ce36ff011a887b62b6efdaa7d2c4742712e08223d467c07461d37ce8e1348c3d9d1f187

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
